
module.exports = {
  GET_PROJECTS_BEGINS: 'GET_PROJECTS_BEGINS',
  GET_PROJECTS_ERROR: 'GET_PROJECTS_ERROR',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_PROJECT_IMAGE: 'DELETE_PROJECT_IMAGE',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  SET_FORM: 'SET_FORM',
  UPDATE_FORM: 'UPDATE_FORM',
  CLEAR_FORM: 'CLEAR_FORM',
  SET_PROJECT_IMAGE: 'SET_PROJECT_IMAGE',
  
}